version: '2'
services:
  db:
    image: "postgres"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 0p9o8i7U
      POSTGRES_USER: foodcalcuser
      POSTGRES_DB: fooddb
  dataloader:
    build: ./dataloader
    links:
      - "db"
  adminer:
    image: adminer
    ports:
        - 8080:8080
    links:
      - "db"
#  web:
#    build: .
#    ports:
#     - "5000:5000"
#  redis:
#    image: "redis:alpine"
